name: E2E
on: push

env:
  GOPATH: /home/runner/go
  AVAPATH: src/github.com/ava-labs
  ACTIONS_RUNTIME_URL: 
  ACTIONS_RUNTIME_TOKEN: 
  ACTIONS_CACHE_URL: 

jobs:
  e2e:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout AvalancheJS
        uses: actions/checkout@v2
        with: 
          repository: 'ava-labs/avalanchejs'
      - name: Install dependencies
<<<<<<< HEAD
        run: apt update && apt install zstd git build-essential nodejs -y
=======
        run: sudo apt update && sudo apt install zstd git build-essential nodejs -y
>>>>>>> development
      - name: Install NodeJS dependencies
        run: yarn install --frozen-lockfile
      - name: Setup GoLang Version
        uses: actions/setup-go@v1
        with:
          go-version: '1.17.9'
      - name: Setup GOPATH and AVAPATH
        run : |
          mkdir -p $GOPATH
          mkdir -p $GOPATH/$AVAPATH
      - name: Install autoremove
<<<<<<< HEAD
        run: apt-get autoremove -y
=======
        run: sudo apt-get autoremove -y
>>>>>>> development
      - name: Clone and Build AvalancheGo
        run : |
          cd $GOPATH
          cd $AVAPATH
          git clone https://github.com/ava-labs/avalanchego
          cd avalanchego
          ./scripts/build.sh
      - name: Checkout ANR
        run : |
          cd $GOPATH
          cd $AVAPATH
          git clone https://github.com/ava-labs/avalanche-network-runner
      - name: Starting ANR
        run: |
          cd $GOPATH
          cd $AVAPATH
          cd avalanche-network-runner
          git checkout v1.0.12
          go run ./examples/local/fivenodenetwork/main.go &
      - name: AvalancheJS E2E Test
        env: 
          AVALANCHEGO_IP: localhost
          AVALANCHEGO_PORT: 9650
        run: sleep 60 && yarn test -i --roots e2e_tests